name: XcubUtils
main: fr.quinou.xcubutils.Main
version: 1.0
author: Quinou
description: Xcub Utils
website: www.google.fr
commands:
  getcoin:
    description: Voir son argent
    usage: /<command> <online_player>
  givemoney:
    description: GiveMoney
    usage: /<command>
  setmoney:
    description: GiveMoney
    usage: /<command>